version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: food-db-test
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: food_test
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
    ports:
      - "3306:3306"
    volumes:
      - ./scripts/db/init:/docker-entrypoint-initdb.d
    networks:
      - food-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: food-redis-test
    command: redis-server --requirepass test_redis
    ports:
      - "6379:6379"
    networks:
      - food-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: food-backend-test
    environment:
      SPRING_PROFILES_ACTIVE: test
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: food_test
      DB_USER: test_user
      DB_PASSWORD: test_pass
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: test_redis
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - food-network
    volumes:
      - ./logs:/app/logs

networks:
  food-network:
    driver: bridge